### ISSUE TITLE
Major upgrade in a boot environment

### ISSUE THREAD

**Issue by grahamperrin** [hukl/freebsd-toolbox#12]
Re: <https://github.com/hukl/freebsd-toolbox/blob/master/commands.md#boot-environments>

You might like to check that on-screen directions during the routine do not contradict what's required for this approach to upgrading …

**Comment by hukl** [comment]
Not sure what you mean by that. This is just a short command reference. There is an upgrade document based on https://klarasystems.com/articles/managing-boot-environments/
