### ISSUE TITLE
search for ports: why not use 'make search name=xyz'?

### ISSUE THREAD

**Issue by mgumz** [hukl/freebsd-toolbox#2]
in line 74 of commands.md you suggest to locate a port by using 'locate'. 

```
$> locate fluxbox | grep ports
locate: database too small: /var/db/locate.database
Run /usr/libexec/locate.updatedb
```

are there any reasons to rely on a locate.database and not to use make:

```
$> cd /usr/ports
$> make search name=fluxbox
```

?

the 'search' target of the ports-makefile is pretty useful:

```
$> make search
The search target requires a keyword parameter or name parameter,
e.g.: "make search key=somekeyword"
or    "make search name=somekeyword"
```

**Comment by hukl** [comment]
hmm didn't know about this one - will look into it and add it - thnx!

**Comment by mgumz** [comment]
done looking?

**Comment by hukl** [comment]
Well the locate command works anywhere - the make search only works in /usr/ports/ right?

**Comment by mgumz** [comment]
`locate` works only for paths configured to be in the /var/db/locate.database (see https://www.freebsd.org/cgi/man.cgi?locate(1) )

`make search` works exactly on the ports-tree you have underneath your fingertips right now.

**Comment by hukl** [comment]
The ports tree is by default included :) But yeah - I can add make search as well ;)

**Comment by mgumz** [comment]
you could also close the ticket as invalid to get me off your back ...
